---
title: "Problem 2"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(p8105.datasets)
library(dplyr)
```

# Load Dataset
```{r}
data(instacart)
```

# Scatter Plot: Order Hour of Day vs Days Since Prior Order
```{r}
scatter_data <- instacart %>% 
  sample_n(1000) %>% 
  filter(!is.na(days_since_prior_order))

plot_ly(data = scatter_data, 
        x = ~order_hour_of_day, 
        y = ~days_since_prior_order, 
        type = 'scatter', 
        mode = 'markers',
        color = ~reordered,
        colors = c('pink', 'lightblue'),
        marker = list(size = 10, opacity = 0.5)) %>%
  layout(title = 'Order Hour of Day vs Days Since Prior Order',
         xaxis = list(title = 'Order Hour of Day'),
         yaxis = list(title = 'Days Since Prior Order'))
```

# Bar Plot: Orders by Day of Week
```{r}
bar_data <- instacart %>%
  group_by(order_dow) %>%
  summarise(count = n()) %>%
  arrange(order_dow)

plot_ly(data = bar_data, 
        x = ~order_dow, 
        y = ~count, 
        type = 'bar',
        marker = list(color = 'lightblue', 
                      line = list(color = 'pink', width = 1.5))) %>%
  layout(title = 'Orders by Day of Week',
         xaxis = list(title = 'Day of Week'),
         yaxis = list(title = 'Number of Orders'))
```

# Box Plot: Order Hour Distribution by Department
```{r}
box_data <- instacart %>% 
  sample_n(1000) %>% 
  group_by(department) %>% 
  filter(n() > 30) %>% 
  ungroup()

plot_ly(data = box_data, 
        y = ~order_hour_of_day, 
        color = ~department, 
        type = 'box') %>%
  layout(title = 'Order Hour Distribution by Department',
         yaxis = list(title = 'Order Hour of Day'))
```

